---
# Instalação do MongoDB e configuração do replicaSet
- name: Pré Requisitos
  block:
    - name: Instalação de utilitários
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - gnupg
        - curl

    - name: Importação de chave pública
      shell: |
        if [ ! -f /usr/share/keyrings/mongodb-server-8.0.gpg ]; then
          curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
        fi

    - name: Criação do arquivo de lista
      shell: "echo \"deb [ signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/8.0 main\" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list"

    - name: Atualização dos pacotes
      apt:
        update_cache: yes

- name: Instalação do MongoDB
  package:
    name: mongodb-org
    state: present

- name: Copia o arquivo de configuração mongod.conf para o nó
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644

- name: Copia o código init-rs.js para inicializar o replicaSet
  template:
    src: templates/init-rs.js.j2
    dest: /tmp/init-rs.js
    mode: 0644
  when: mongodb_primary is defined and mongodb_primary

- name: Configuração do MongoDB
  block:
    - name: Criação do diretório de dados
      file:
        path: "{{ mongodb_path }}"
        owner: mongodb
        group: mongodb
        mode: 0755
        state: directory

    - name: Configuração do keyfile se não for adotado SSL
      copy:
        dest: "{{ keyfile_path }}"
        content: "{{ keyfile_content }}"
        owner: mongodb
        group: mongodb
        mode: 0400
      when: not use_tls | bool

    - name: Inicialização do serviço
      service:
        name: mongod
        enabled: yes
        state: restarted

    - name: Aguardando a inicialização do serviço
      pause:
        seconds: 60

    - name: Inicialização do replicaSet
      shell: "mongosh {{ mongodb_extra_args | default('') }} --port {{ rs_port }} < /tmp/init-rs.js"
      when: mongodb_primary is defined and mongodb_primary

    - name: Aguardando a inicialização do replicaSet
      pause:
        seconds: 15

- name: Criação de usuário para administração da instância
  block:
    - name: Preparando a criação do usuário root
      template:
        src: templates/createRoot.js.j2
        dest: /tmp/createRoot.js
        mode: 0644
      when: mongodb_primary is defined and mongodb_primary

    - name: Criação do usuário root
      shell: "mongosh admin {{ mongodb_extra_args | default('') }} --port {{ rs_port }} < /tmp/createRoot.js"
      when: mongodb_primary is defined and mongodb_primary