mongodb_root_password: "{{ lookup('env', 'MONGODB_ROOT_PASSWORD') }}"

rs_port: 27017

mongodb_path: /data/db
mongodb_log_path: /var/log/mongodb

#mongodb_extra_args: Definição de argumentos, tais como --tls --tlsCertificateKeyFile /path/client.pem --tlsCAFile /path/caToValidateServerCertificates.pem

use_tls: false

# Relevante, desde que use_tls: false
keyfile_path: /data/keyfile
keyfile_content: "{{ lookup('env', 'KEYFILE_CONTENT') }}"