apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-map
data:
  username: admin

---

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret 
type: Opaque
data:
  password: UGFzc3dvcmQkMTIzNDU2 # Password$123456